# Site settings
title: Kevin Neumann
email: kevin@kneumann.org
description: "I'm a software developer."
baseurl: ""
url: "https://www.kneumann.org"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
